name: DataLinter PULL_REQUEST run
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  PROJECT_DIR_NAME: "target_R_project"
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    permissions:
      #for comment creation and comment update
      pull-requests: write 
      issues: write
    name: DataLinter Docker ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current project repository
        uses: actions/checkout@v6
        with:
          path: ${{ env.PROJECT_DIR_NAME }}

      - id: datalinter
        name: Run DataLinter
        uses: ./.github/actions/datalinter
        with:
          data-path: 'test/data/imbalanced_data.csv'
          code-path: 'test/code/r_snippet_imbalanced.r'
          config-path: 'config/r_modelling_config.toml'

      - name: Print output
        run: echo "${{ steps.datalinter.outputs.result }}"

      - name: Edit PR comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ${{ steps.datalinter.outputs.result }}
          comment_tag: datalinter
